server:
  port: ${PORT:8081}

spring:
  application:
    name: catalogo-api
  datasource:
    # Base propia del microservicio (puede estar en la misma instancia RDS que pedidos).
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:catalogodb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/413875c7-b2d6-4bc6-93ee-071e4f43a25e/v2.0
          jwk-set-uri: https://login.microsoftonline.com/413875c7-b2d6-4bc6-93ee-071e4f43a25e/discovery/v2.0/keys
          # Solo se aceptan tokens emitidos para la API (App_DSY1107_API).
          audiences:
            - fe49fbff-96c3-4146-b54e-a81b1d2a2379
            - api://fe49fbff-96c3-4146-b54e-a81b1d2a2379
